/**
 * Enumeration of active feature flags.
 */
export enum FeatureFlag {
  VFF_AI_SEGMENTATION = "VFF_AI_SEGMENTATION",
  VFF_MULTIMODAL = "VFF_MULTIMODAL",
  VFF_POLYLINE_ANNOTATION = "VFF_POLYLINE_ANNOTATION",
  VFF_ONTOLOGY_CA = "VFF_ONTOLOGY_CA",
}
