export enum SmartFormInputs {
  String = "string",
  Number = "number",
  Integer = "integer",
  Boolean = "boolean",
  Null = "null",
  Object = "object",
  Array = "array",
  OneOf = "oneOf",
}

export enum SmartFormComponents {
  FieldView = "FieldView",
  CheckboxView = "CheckboxView",
  DropdownView = "DropdownView",
  Dropdown = "Dropdown",
  RadioView = "RadioView",
  RadioGroup = "RadioGroup",
  AutocompleteView = "AutocompleteView",
  ColorView = "ColorView",
  CodeView = "CodeView",
  JSONView = "JSONView",
  FileView = "FileView",
  TabsView = "TabsView",
  ObjectView = "ObjectView",
  GridView = "GridView",
  ListView = "ListView",
  TupleView = "TupleView",
  MapView = "MapView",
  OneOfView = "OneOfView",
  ProgressView = "ProgressView",
  LinkView = "LinkView",
  DashboardView = "DashboardView",
  FileExplorerView = "FileExplorerView",
  LazyFieldView = "LazyFieldView",
  MenuView = "MenuView",
  ButtonView = "ButtonView",
  NoticeView = "NoticeView",
  MarkdownView = "MarkdownView",
  PlotlyView = "PlotlyView",
}
