language: "en"
early_access: false
tone_instructions: "Be concise and directive. Prioritize correctness, safety, and performance over stylistic nits."
reviews:
  profile: "assertive"
  request_changes_workflow: false
  changed_files_summary: false
  auto_assign_reviewers: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  path_filters:
    - "!**/*.xml"
    - "!**/*.json"
    - "!**/*.svg"
    - "!**/*.png"
    - "!**/*.jpg"
    - "!**/*.gif"
    - "!**/*.lock"
    - "!**/node_modules/**"
    - "!**/dist/**"
    - "!**/build/**"
    - "!**/.next/**"
    - "!**/coverage/**"
    - "!**/__generated__/**"
    - "!**/generated/**"
  path_instructions:
    - path: "**/*.{ts,tsx}"
      instructions: "Review the Typescript and React code for conformity with best practices in React, Recoil, Graphql, and Typescript. Highlight any deviations."
    - path: "**/*.{py}"
      instructions: "Review the Python code for conformity with best practices in Python3. Highlight any deviations."
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
      - "DRAFT"
    drafts: false
    base_branches:
      - "develop"
      - "main"
      - "release/.*"
      - "feat/.*"
chat:
  auto_reply: true
knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/CODING_STANDARDS.md"
