repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        language: system
        entry: >-
          uv run --locked --no-sync ruff check
          --config pyproject.toml
        types_or: [python, pyi]
      - id: ty-check
        name: ty check
        language: system
        entry: uv run --locked --no-sync ty check
        pass_filenames: false
        types_or: [python, pyi]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        language: system
        files: \.py$
        entry: pylint
        args: ["--errors-only"]
        exclude: (^docs/theme/|app/|(^|.*/)__generated__/)
  - repo: local
    hooks:
      - id: ipynb-strip
        name: ipynb-strip
        language: system
        files: \.ipynb$
        exclude: ^docs/ # *do* commit ipynb outputs in `docs/`
        entry: jupyter nbconvert --clear-output --ClearOutputPreprocessor.enabled=True
        args: ["--log-level=ERROR"]
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        language: system
        entry: app/node_modules/.bin/prettier --write --ignore-unknown
        files: \.(ts|js|jsx|tsx|json|css|scss|md)$
        exclude: ^docs/theme/
