name: 'Setup FFmpeg with retries'
description: 'Installs FFmpeg with retry logic'
inputs:
  github-token:
    description: 'GitHub Token (required by "FedericoCarboni/setup-ffmpeg@v3")'
    required: true
  retries:
    description: 'Number of retry attempts (default 5)'
    default: '5'
  delay:
    description: 'Delay in seconds between retries (default 5)'
    default: '5'

runs:
  using: 'composite'
  steps:
    - name: Retry FFmpeg Setup
      id: setup-ffmpeg
      run: |
        retries=${{ inputs.retries }}
        delay=${{ inputs.delay }}
        count=1
        success=false
        
        while [ $count -le $retries ]; do
          echo "Attempt $count of $retries..."
          
          # Try to run the setup-ffmpeg action
          npx -c "gh action run FedericoCarboni/setup-ffmpeg@v3 --github-token ${{ inputs.github-token }}"
          
          # Check the exit code of the previous command
          if [ $? -eq 0 ]; then
            success=true
            break
          else
            echo "Setup failed, retrying..."
            count=$((count + 1))
            if [ $count -le $retries ]; then
              echo "Waiting for $delay seconds before retrying..."
              sleep $delay
            fi
          fi
        done
        
        if [ "$success" = false ]; then
          echo "FFmpeg setup failed after $retries attempts"
          exit 1
        fi
