name: Feature Request 💡
description: Use this template for feature and enhancement proposals
title: "[FR] "
labels:
  - feature

body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/voxel51/fiftyone/blob/develop/ISSUE_POLICY.md) for information on what types of issues we address.

  - type: textarea
    id: proposal-summary
    validations:
      required: true
    attributes:
      label: 📋 Proposal Summary
      description: |
        In a few sentences, provide a clear, high-level description of the feature request.
      placeholder: Describe the feature you'd like to see

  - type: textarea
    id: motivation
    validations:
      required: true
    attributes:
      label: 💡 Motivation
      description: |
        - What is the use case for this feature?
        - Why is this use case valuable to support for FiftyOne users in general?
        - Why is this use case valuable to support for your project(s) or organization?
        - Why is it currently difficult to achieve this use case?
      placeholder: Explain why this feature would be valuable

  - type: checkboxes
    id: affected-areas
    validations:
      required: true
    attributes:
      label: 🎯 What areas of FiftyOne does this feature affect?
      description: Select all that apply.
      options:
        - label: "App: FiftyOne application"
        - label: "Core: Core `fiftyone` Python library"
        - label: "Server: FiftyOne server"

  - type: textarea
    id: details
    attributes:
      label: 📝 Details
      description: |
        Use this section to include any additional information about the feature. If you
        have a proposal for how to implement this feature, please include it here.
      placeholder: Additional details or implementation proposals

  - type: checkboxes
    id: contribute
    validations:
      required: true
    attributes:
      label: 🚀 Willingness to contribute
      description: |
        The FiftyOne Community welcomes contributions! Would you or another member of your
        organization be willing to contribute an implementation of this feature?
      options:
        - label: Yes. I can contribute this feature independently
        - label: Yes. I would be willing to contribute this feature with guidance from the FiftyOne community
        - label: No. I cannot contribute this feature at this time

  - type: markdown
    attributes:
      value: |
        ### 📚 Helpful Resources
        - 📖 [FiftyOne Documentation](https://docs.voxel51.com/)
        - 💬 [Discord Community](https://discord.gg/fiftyone-community)
        - 🎬 [YouTube Channel](https://www.youtube.com/@voxel51)
