approvedGitRepositories:
  - "**"



compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

catalog:
  "@storybook/addon-essentials": ^8
  "@storybook/addon-interactions": ^8
  "@storybook/addon-links": ^8
  "@storybook/react": ^8
  "@storybook/react-vite": ^8
  "@vitejs/plugin-react": ^6.0.4
  "@vitest/coverage-v8": ^4.1.10
  "@vitest/ui": ^4.1.10
  eslint: ^8.28.0
  prettier: ~3.8.4
  storybook: ^8
  vite: ^8.1.5
  vite-plugin-eslint: ^1.8.1
  vite-plugin-externals: ^0.5.0
  vite-plugin-relay: ^2.1.0
  vite-plugin-rewrite-all: ^1.0.2
  vite-plugin-svgr: ^5.2.0
  vite-plugin-wasm: ^3.6.0
  vitest: ^4.1.10

catalogs:
  eslint9:
    eslint: 9.7.0
