approvedGitRepositories:
  - "**"

catalog:
  "@eslint/compat": ^1.1.1
  "@microsoft/fetch-event-source": ^2.0.1
  "@mui/icons-material": ^5.16.7
  "@mui/material": ^5.9.0
  "@react-three/fiber": ^8.18.0
  "@storybook/addon-essentials": ^8
  "@storybook/addon-interactions": ^8
  "@storybook/addon-links": ^8
  "@storybook/react": ^8
  "@storybook/react-vite": ^8
  "@testing-library/dom": ^10.4.0
  "@types/lodash": ^4.14.182
  "@types/mime": ^2.0.3
  "@types/styled-components": ^5.1.23
  "@vitejs/plugin-react": ^6.0.4
  "@vitest/coverage-v8": ^4.1.10
  "@vitest/ui": ^4.1.10
  buffer: ^6.0.3
  colormap: ^2.3.2
  eslint: ^8.28.0
  fast-json-patch: ^3.1.1
  globals: ^15.8.0
  history: ^5.3.0
  jotai: ^2.20.1
  jotai-effect: ^2.2.3
  jotai-family: ^1.0.2
  lodash: ^4.18.1
  lru-cache: ^11.0.1
  mime: ^2.5.2
  numeral: ^2.0.6
  onnxruntime-web: ^1.24.3
  prettier: ~3.8.4
  re-resizable: ^6.9.17
  react-color: ^2.19.3
  react-error-boundary: ^3.1.4
  react-input-autosize: ^3.0.0
  react-laag: ^2.0.3
  react-markdown: ^8.0.7
  react-syntax-highlighter: ^15.5.0
  react-use-measure: ^2.0.1
  react-uuid: ^1.0.2
  recoil: 0.7.7
  recoil-relay: ^0.1.0
  resize-observer-polyfill: ^1.5.1
  rollup-plugin-polyfill-node: ^0.6.2
  storybook: ^8
  typescript: ^4.9.5
  typescript-eslint: ^7.17.0
  use-resize-observer: ^9.0.2
  uuid: ^14.0.0
  vite: ^8.1.5
  vite-plugin-externals: ^0.6.2
  vite-plugin-relay: ^2.1.0
  vite-plugin-svgr: ^5.2.0
  vite-plugin-wasm: ^3.6.0
  vitest: ^4.1.10

catalogs:
  eslint9:
    eslint: 9.7.0

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0
