import * as THREE from "three";
import * as TSL from "three/tsl";
import { MeshBasicNodeMaterial } from "three/webgpu";

import type { ImageTextureHandle } from "./Base2dScene";

const MAX_FINITE_FLOAT32 = 3.4028234663852886e38;
const UINT8_MAX = 255;

export interface DepthImageMaterialOptions {
  readonly depthTest?: boolean;
  readonly depthWrite?: boolean;
  readonly opacity?: number;
  readonly side?: THREE.Side;
}

/**
 * Builds the WebGPU material for a native single-channel depth texture.
 * Invalid values remain transparent and valid samples use the decoder's
 * per-frame min/max grayscale mapping, including its uint8 quantization.
 */
export function createDepthImageMaterial(
  handle: ImageTextureHandle,
  {
    depthTest = true,
    depthWrite = true,
    opacity = 1,
    side = THREE.FrontSide,
  }: DepthImageMaterialOptions = {},
): MeshBasicNodeMaterial {
  const range = handle.depthDisplay;
  if (!range) {
    throw new Error("Depth image material requires a depth texture handle");
  }

  const material = new MeshBasicNodeMaterial();
  material.depthTest = depthTest;
  material.depthWrite = depthWrite;
  material.side = side;
  material.toneMapped = false;
  material.transparent = true;

  const sample = TSL.texture(handle.texture, TSL.uv()).x;
  const hasRange =
    range.minSampleValue !== null && range.maxSampleValue !== null;
  const valid = TSL.and(
    TSL.greaterThan(sample, 0),
    TSL.equal(sample, sample),
    TSL.lessThanEqual(TSL.abs(sample), MAX_FINITE_FLOAT32),
  );
  const normalized = !hasRange
    ? TSL.float(0)
    : range.minSampleValue === range.maxSampleValue
      ? TSL.float(1)
      : TSL.clamp(
          sample
            .sub(range.minSampleValue)
            .div(range.maxSampleValue - range.minSampleValue),
          0,
          1,
        );
  // Math.round is half-up; shader round may use ties-to-even.
  const byteShade = TSL.floor(normalized.mul(UINT8_MAX).add(0.5)).div(
    UINT8_MAX,
  );
  // The former RGBA texture was tagged sRGB. Convert the generated byte shade
  // to the working space so the final display transfer produces the same gray.
  material.colorNode = TSL.colorSpaceToWorking(
    TSL.vec3(byteShade),
    THREE.SRGBColorSpace,
  );
  material.opacityNode = hasRange
    ? TSL.select(valid, opacity, 0)
    : TSL.float(0);
  return material;
}
