# If you are using the `Building ad Deploying FiftyOne Teams (internal use)` doc
# # https://docs.google.com/document/d/1Tn-gf4XKKF3P2fUIVPF0xGDuidbI04WvKmnPlPKTVSQ
# Then `GPT_PLUGIN_IMAGE_NAME` should already be set, just reuse it here...
ARG GPT_PLUGIN_IMAGE_NAME
ARG PYTHON_VERSION=3.10

FROM python:${PYTHON_VERSION} as wheelhouse
ARG PIP_INDEX_URL=https://pypi.org/simple

RUN pip wheel --wheel-dir=/tmp/wheels sentence_transformers pyperclip darwin-fiftyone

FROM ${GPT_PLUGIN_IMAGE_NAME} as internalrelease

RUN --mount=type=cache,from=wheelhouse,target=/wheelhouse,ro \
    pip --no-cache-dir install -q --no-index \
    --find-links=/wheelhouse/tmp/wheels sentence_transformers pyperclip darwin-fiftyone

# run as the voxel51 user
USER 1000:1000

#
# Serve the app
#
CMD hypercorn fiftyone.teams.app:app --bind "${FIFTYONE_DEFAULT_APP_ADDRESS:-0.0.0.0}":"${FIFTYONE_DEFAULT_APP_PORT:-5151}" --workers "${HYPERCORN_WORKERS:-4}"
