# If you are using the `Building and Deploying FiftyOne Teams (internal use)` doc
# https://docs.google.com/document/d/1Tn-gf4XKKF3P2fUIVPF0xGDuidbI04WvKmnPlPKTVSQ
# Then `TEAMS_IMAGE_NAME` should already be set, just reuse it here...
ARG TEAMS_IMAGE_NAME
ARG PYTHON_VERSION=3.10

FROM python:${PYTHON_VERSION} as wheelhouse

RUN pip wheel --wheel-dir=/tmp/wheels chromadb==0.3.22 langchain==0.0.166 openai==0.27.6 pandas==1.3.5


FROM ${TEAMS_IMAGE_NAME} as gptrelease

RUN --mount=type=cache,from=wheelhouse,target=/wheelhouse,ro \
    pip --no-cache-dir install --no-index \
    --find-links=/wheelhouse/tmp/wheels chromadb==0.3.22 langchain==0.0.166 openai==0.27.6 pandas==1.3.5

# run as the voxel51 user
USER voxel51

#
# Serve the app
#
CMD hypercorn fiftyone.teams.app:app --bind "${FIFTYONE_DEFAULT_APP_ADDRESS:-0.0.0.0}":"${FIFTYONE_DEFAULT_APP_PORT:-5151}"
