# If you are using the `Building and Deploying FiftyOne Teams (internal use)` doc
# https://docs.google.com/document/d/1Tn-gf4XKKF3P2fUIVPF0xGDuidbI04WvKmnPlPKTVSQ
# Then `TEAMS_IMAGE_NAME` should already be set, just reuse it here...
ARG TORCH_IMAGE_NAME=fiftyone-app-torch:local
ARG PYTHON_VERSION=3.11

FROM python:${PYTHON_VERSION} AS wheelhouse
ARG PIP_INDEX_URL=https://pypi.org/simple

# Why are these pinned?
# https://community.openai.com/t/error-with-openai-1-56-0-client-init-got-an-unexpected-keyword-argument-proxies/1040332/2
# We should unpin these and test during a non-release cycle
# Pydantic 2.11 seems to be broken with strawberry at the moment, ignore anything greater than it.
# Revisit this if we update strawberry!
RUN pip install -U pip wheel setuptools && \
    pip wheel --wheel-dir=/tmp/wheels \
      "langchain-community==0.3.5" \
      "langchain-core==0.3.15" \
      "langchain-openai==0.2.6" \
      "langchain==0.3.7" \
      "openai==1.54.3" \
      "tiktoken>=0.7.0" \
      "httpx==0.27.2" \
      "pydantic>=2.0,<2.11" \
      google-cloud-bigquery \
      pandas \
      scipy

FROM ${TORCH_IMAGE_NAME} AS gptrelease

RUN --mount=type=cache,from=wheelhouse,target=/wheelhouse,ro \
    pip install --no-cache-dir -q --no-index \
      --find-links=/wheelhouse/tmp/wheels \
      "langchain-community==0.3.5" \
      "langchain-core==0.3.15" \
      "langchain-openai==0.2.6" \
      "langchain==0.3.7" \
      "openai==1.54.3" \
      "tiktoken>=0.7.0" \
      "httpx==0.27.2" \
      "pydantic>=2.0,<2.11" \
      google-cloud-bigquery \
      pandas \
      scipy

# run as the voxel51 user
USER 1000:1000

# Default hypercorn settings.
ENV HYPERCORN_WORKERS=4 

#
# Serve the app. Kept as a CMD and not an 
# ENTRYPOINT so existing customers not impacted
# if they override these
#
CMD [ "/opt/entrypoint.sh" ]
