# If you are using the `Building and Deploying FiftyOne Teams (internal use)` doc
# https://docs.google.com/document/d/1Tn-gf4XKKF3P2fUIVPF0xGDuidbI04WvKmnPlPKTVSQ
# Then `TEAMS_IMAGE_NAME` should already be set, just reuse it here...
ARG TEAMS_IMAGE_NAME

FROM ${TEAMS_IMAGE_NAME} as wheelhouse

RUN pip wheel --wheel-dir=/tmp/wheels torchvision==0.14.1 torch==1.13.1


FROM ${TEAMS_IMAGE_NAME} as torchrelease

RUN --mount=type=cache,from=wheelhouse,target=/wheelhouse,ro \
    pip --no-cache-dir install -q --no-index \
    --find-links=/wheelhouse/tmp/wheels torchvision==0.14.1 torch==1.13.1 \
    && mkdir -p "${HOME}/fiftyone/__models__"

# You must download the `__models__` directory first:
#   gcloud storage cp -r gs://fiftyone-app-release-dependencies/__models__ .
# Please see https://docs.google.com/document/d/1Tn-gf4XKKF3P2fUIVPF0xGDuidbI04WvKmnPlPKTVSQ/edit?pli=1#heading=h.74je1akw3gzg
COPY --chown=voxel51:voxel51 __models__ fiftyone/__models__

# run as the voxel51 user
USER voxel51

#
# Serve the app
#
CMD hypercorn fiftyone.teams.app:app --bind "${FIFTYONE_DEFAULT_APP_ADDRESS:-0.0.0.0}":"${FIFTYONE_DEFAULT_APP_PORT:-5151}"
