# If you are using the `Building and Deploying FiftyOne Teams (internal use)` doc
# https://docs.google.com/document/d/1Tn-gf4XKKF3P2fUIVPF0xGDuidbI04WvKmnPlPKTVSQ
# Then `TORCH_IMAGE_NAME` should already be set, just reuse it here...
ARG TORCH_IMAGE_NAME=fiftyone-app-torch:local
ARG PYTHON_VERSION=3.11

FROM python:${PYTHON_VERSION} AS wheelhouse
ARG PIP_INDEX_URL=https://pypi.org/simple

# Requirements for pip wheel
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        gdal-bin \
        libgdal-dev \
        python3-dev \
        protobuf-compiler && \
    rm -rf /var/lib/apt/lists/*

# pycocotools==2.0.8  seems required for super-gradients
RUN pip install -U pip wheel setuptools && \
    pip wheel --wheel-dir=/tmp/wheels \
        open3d \
        open_clip_torch \
        "pycocotools==2.0.8" \
        pydicom \
        pyproj \
        rasterio \
        segment-anything \
        super-gradients \
        shapely \
        transformers \
        "ultralytics>=8.3.0" \
        "umap-learn>=0.5"

RUN pip wheel --no-build-isolation \
    --wheel-dir=/tmp/wheels \
        sam2

FROM ${TORCH_IMAGE_NAME} AS teamscvfullrelease

USER root

# Some dependenices require GDAL headers
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gdal-bin \
        libgdal-dev && \
    rm -rf /var/lib/apt/lists/*

# run as the voxel51 user
USER 1000:1000

RUN --mount=type=cache,from=wheelhouse,target=/wheelhouse,ro \
    pip --no-cache-dir install -q --no-index \
    --find-links=/wheelhouse/tmp/wheels \
    open3d \
    open_clip_torch \
    pycocotools \
    pydicom \
    pyproj \
    rasterio \
    sam2 \
    segment-anything \
    shapely \
    super-gradients \
    transformers \
    "ultralytics>=8.3.0" \
    "umap-learn>=0.5"

# run as the voxel51 user
USER 1000:1000

# Default hypercorn settings.
ENV HYPERCORN_WORKERS=4

#
# Serve the app. Kept as a CMD and not an
# ENTRYPOINT so existing customers not impacted
# if they override these
#
CMD [ "/opt/entrypoint.sh" ]
