# If you are using the `Building and Deploying FiftyOne Teams (internal use)` doc
# https://docs.google.com/document/d/1Tn-gf4XKKF3P2fUIVPF0xGDuidbI04WvKmnPlPKTVSQ
# Then `TEAMS_IMAGE_NAME` should already be set, just reuse it here...
ARG TEAMS_IMAGE_NAME

FROM ${TEAMS_IMAGE_NAME} as wheelhouse

RUN pip wheel --wheel-dir=/tmp/wheels torchvision==0.14.1 torch==1.13.1


FROM ${TEAMS_IMAGE_NAME} as torchrelease

RUN --mount=type=cache,from=wheelhouse,target=/wheelhouse,ro \
    pip --no-cache-dir install --no-index \
    --find-links=/wheelhouse/tmp/wheels torchvision==0.14.1 torch==1.13.1

# run as the voxel51 user
USER voxel51

#
# Serve the app
#
CMD hypercorn fiftyone.teams.app:app --bind "${FIFTYONE_DEFAULT_APP_ADDRESS:-0.0.0.0}":"${FIFTYONE_DEFAULT_APP_PORT:-5151}"
