# If you are using the `Building and Deploying FiftyOne Teams (internal use)` doc
# https://docs.google.com/document/d/1Tn-gf4XKKF3P2fUIVPF0xGDuidbI04WvKmnPlPKTVSQ
# Then `CV_BASE_IMAGE_NAME` should already be set, just reuse it here...
ARG CV_BASE_IMAGE_NAME=fiftyone-teams-cv-full:local
ARG PYTHON_VERSION=3.11

FROM python:${PYTHON_VERSION} AS wheelhouse
ARG PIP_INDEX_URL=https://pypi.org/simple

RUN pip install -U pip wheel setuptools && \
    pip wheel --wheel-dir=/tmp/wheels qdrant-client open-clip-torch "pydantic>=2.0,<2.11"


FROM ${CV_BASE_IMAGE_NAME} AS zefrplugins

RUN --mount=type=cache,from=wheelhouse,target=/wheelhouse,ro \
    pip --no-cache-dir install -q --no-index \
    --find-links=/wheelhouse/tmp/wheels qdrant-client open-clip-torch "pydantic>=2.0,<2.11"


# run as the voxel51 user
USER 1000:1000

# Default hypercorn settings.
ENV HYPERCORN_WORKERS=4 

#
# Serve the app. Kept as a CMD and not an 
# ENTRYPOINT so existing customers not impacted
# if they override these
#
CMD [ "/opt/entrypoint.sh" ]
