"""
Voodo design system color palette.

AUTO-GENERATED by ``tools/sync_voodoo_palette.py`` -- do not edit by hand.
Run that script to pick up design system changes.

| Copyright 2017-2025, Voxel51, Inc.
| `voxel51.com <https://voxel51.com/>`_
|
"""

# The App's default color pool, in the order colors are handed out
COLOR_POOL = [
    "#FF6D04",  # 1: orange 500
    "#2563EB",  # 2: blue 500
    "#1E7D45",  # 3: green 500
    "#8B5CF6",  # 4: purple 500
    "#DB2777",  # 5: pink 500
    "#D97706",  # 6: yellow 500
    "#0D9488",  # 7: teal 500
    "#6F42C1",  # 8: purple 600
    "#532E91",  # 9: purple 700
    "#C33636",  # 10: red 500
    "#B26003",  # 11: yellow 600
    "#166638",  # 12: green 600
]
