/**
 * Copyright 2017-2026, Voxel51, Inc.
 */

import { act, renderHook } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";

const hoisted = vi.hoisted(() => ({
  supplyAnnotationDeltas: vi.fn(),
  patchSample: vi.fn(),
  eventBusDispatch: vi.fn(),
  useRecoilValue: vi.fn(),
}));

vi.mock("recoil", () => ({
  useRecoilValue: (key: unknown) => hoisted.useRecoilValue(key),
}));

vi.mock("@fiftyone/state", () => ({
  isGeneratedView: "isGeneratedView-recoil-key",
}));

vi.mock("./useAnnotationDeltaSupplier", () => ({
  useAnnotationDeltaSupplier: () => hoisted.supplyAnnotationDeltas,
}));

vi.mock("../hooks", () => ({
  useAnnotationEventBus: () => ({ dispatch: hoisted.eventBusDispatch }),
  usePatchSample: () => hoisted.patchSample,
}));

import { usePersistAnnotationDeltas } from "./usePersistAnnotationDeltas";

const DELTAS = [{ op: "replace", path: "/a", value: 1 }];
const METADATA = { labelId: "lbl-1", labelPath: "predictions" };

describe("usePersistAnnotationDeltas", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    hoisted.useRecoilValue.mockReturnValue(false); // not generated by default
  });

  it("returns null and does nothing else when no deltas are pending", async () => {
    hoisted.supplyAnnotationDeltas.mockReturnValue({
      deltas: [],
      metadata: undefined,
    });
    const { result } = renderHook(() => usePersistAnnotationDeltas());

    let res: unknown;
    await act(async () => {
      res = await result.current();
    });

    expect(res).toBeNull();
    expect(hoisted.eventBusDispatch).not.toHaveBeenCalled();
    expect(hoisted.patchSample).not.toHaveBeenCalled();
  });

  it("non-generated view: dispatches persistenceInFlight then calls patchSample(deltas)", async () => {
    hoisted.supplyAnnotationDeltas.mockReturnValue({
      deltas: DELTAS,
      metadata: undefined,
    });
    hoisted.patchSample.mockResolvedValue(true);
    const { result } = renderHook(() => usePersistAnnotationDeltas());

    let res: unknown;
    await act(async () => {
      res = await result.current();
    });

    expect(hoisted.eventBusDispatch).toHaveBeenCalledTimes(1);
    expect(hoisted.eventBusDispatch).toHaveBeenCalledWith(
      "annotation:persistenceInFlight",
    );
    expect(hoisted.patchSample).toHaveBeenCalledTimes(1);
    expect(hoisted.patchSample).toHaveBeenCalledWith(DELTAS);
    expect(res).toBe(true);
  });

  it("non-generated view: returns false when patchSample resolves to false", async () => {
    hoisted.supplyAnnotationDeltas.mockReturnValue({
      deltas: DELTAS,
      metadata: undefined,
    });
    hoisted.patchSample.mockResolvedValue(false);
    const { result } = renderHook(() => usePersistAnnotationDeltas());

    let res: unknown;
    await act(async () => {
      res = await result.current();
    });

    expect(res).toBe(false);
  });

  it("generated view: includes labelId/labelPath/opType when metadata is supplied", async () => {
    hoisted.useRecoilValue.mockReturnValue(true);
    hoisted.supplyAnnotationDeltas.mockReturnValue({
      deltas: DELTAS,
      metadata: METADATA,
    });
    hoisted.patchSample.mockResolvedValue(true);
    const { result } = renderHook(() => usePersistAnnotationDeltas());

    let res: unknown;
    await act(async () => {
      res = await result.current();
    });

    expect(hoisted.patchSample).toHaveBeenCalledWith(DELTAS, {
      labelId: METADATA.labelId,
      labelPath: METADATA.labelPath,
      opType: "mutate",
    });
    expect(res).toBe(true);
  });

  it("generated view without metadata: warns, returns false, and skips patchSample", async () => {
    const warnSpy = vi.spyOn(console, "warn").mockImplementation(() => {});
    hoisted.useRecoilValue.mockReturnValue(true);
    hoisted.supplyAnnotationDeltas.mockReturnValue({
      deltas: DELTAS,
      metadata: undefined,
    });
    const { result } = renderHook(() => usePersistAnnotationDeltas());

    let res: unknown;
    await act(async () => {
      res = await result.current();
    });

    expect(res).toBe(false);
    expect(hoisted.patchSample).not.toHaveBeenCalled();
    // persistenceInFlight is still dispatched before the metadata check
    expect(hoisted.eventBusDispatch).toHaveBeenCalledWith(
      "annotation:persistenceInFlight",
    );
    expect(warnSpy).toHaveBeenCalledTimes(1);
    warnSpy.mockRestore();
  });
});
