/**
 * Minimal compressed-image descriptor/message fixture.
 *
 * The schema bytes are a FileDescriptorSet built from the canonical Foxglove
 * `foxglove/CompressedImage.proto` schema plus google.protobuf.Timestamp:
 * https://github.com/foxglove/schemas/blob/main/schemas/proto/foxglove/CompressedImage.proto
 * The message bytes encode a JPEG payload with frame id `CAM_TEST`.
 */
export const COMPRESSED_IMAGE_FIXTURE = Object.freeze({
  message: bytes("CggIexCAhLjZARIJZmFrZS1qcGVnGgRqcGVnIghDQU1fVEVTVA=="),
  schemaData: bytes(
    "Cv8BCh9nb29nbGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvEg9nb29nbGUucHJvdG9idWYiOwoJVGltZXN0YW1wEhgKB3NlY29uZHMYASABKANSB3NlY29uZHMSFAoFbmFub3MYAiABKAVSBW5hbm9zQoUBChNjb20uZ29vZ2xlLnByb3RvYnVmQg5UaW1lc3RhbXBQcm90b1ABWjJnb29nbGUuZ29sYW5nLm9yZy9wcm90b2J1Zi90eXBlcy9rbm93bi90aW1lc3RhbXBwYvgBAaICA0dQQqoCHkdvb2dsZS5Qcm90b2J1Zi5XZWxsS25vd25UeXBlc2IGcHJvdG8zCsUBCh5mb3hnbG92ZS9Db21wcmVzc2VkSW1hZ2UucHJvdG8SCGZveGdsb3ZlGh9nb29nbGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvInAKD0NvbXByZXNzZWRJbWFnZRItCgl0aW1lc3RhbXAYASABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEhAKCGZyYW1lX2lkGAQgASgJEgwKBGRhdGEYAiABKAwSDgoGZm9ybWF0GAMgASgJYgZwcm90bzM=",
  ),
});

/**
 * Minimal point-cloud descriptor/message fixture.
 *
 * The schema bytes are a FileDescriptorSet built from the canonical Foxglove
 * `foxglove/PointCloud.proto` dependency graph:
 * https://github.com/foxglove/schemas/blob/main/schemas/proto/foxglove/PointCloud.proto
 * The message bytes encode two XYZ float32 points in frame id `LIDAR_TEST`.
 */
export const POINT_CLOUD_FIXTURE = Object.freeze({
  message: bytes(
    "CggIexCBhLjZARIKTElEQVJfVEVTVCUMAAAAKgUKAXgYByoKCgF5FQQAAAAYByoKCgF6FQgAAAAYBzIYAACAPwAAAEAAAEBAAACAQAAAoEAAAMBA",
  ),
  schemaData: bytes(
    "CpsCCiFmb3hnbG92ZS9QYWNrZWRFbGVtZW50RmllbGQucHJvdG8SCGZveGdsb3ZlIuMBChJQYWNrZWRFbGVtZW50RmllbGQSDAoEbmFtZRgBIAEoCRIOCgZvZmZzZXQYAiABKAcSNgoEdHlwZRgDIAEoDjIoLmZveGdsb3ZlLlBhY2tlZEVsZW1lbnRGaWVsZC5OdW1lcmljVHlwZSJ3CgtOdW1lcmljVHlwZRILCgdVTktOT1dOEAASCQoFVUlOVDgQARIICgRJTlQ4EAISCgoGVUlOVDE2EAMSCQoFSU5UMTYQBBIKCgZVSU5UMzIQBRIJCgVJTlQzMhAGEgsKB0ZMT0FUMzIQBxILCgdGTE9BVDY0EAhiBnByb3RvMwpnChlmb3hnbG92ZS9RdWF0ZXJuaW9uLnByb3RvEghmb3hnbG92ZSI4CgpRdWF0ZXJuaW9uEgkKAXgYASABKAESCQoBeRgCIAEoARIJCgF6GAMgASgBEgkKAXcYBCABKAFiBnByb3RvMwpWChZmb3hnbG92ZS9WZWN0b3IzLnByb3RvEghmb3hnbG92ZSIqCgdWZWN0b3IzEgkKAXgYASABKAESCQoBeRgCIAEoARIJCgF6GAMgASgBYgZwcm90bzMKsgEKE2ZveGdsb3ZlL1Bvc2UucHJvdG8SCGZveGdsb3ZlGhlmb3hnbG92ZS9RdWF0ZXJuaW9uLnByb3RvGhZmb3hnbG92ZS9WZWN0b3IzLnByb3RvIlYKBFBvc2USIwoIcG9zaXRpb24YASABKAsyES5mb3hnbG92ZS5WZWN0b3IzEikKC29yaWVudGF0aW9uGAIgASgLMhQuZm94Z2xvdmUuUXVhdGVybmlvbmIGcHJvdG8zCv8BCh9nb29nbGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvEg9nb29nbGUucHJvdG9idWYiOwoJVGltZXN0YW1wEhgKB3NlY29uZHMYASABKANSB3NlY29uZHMSFAoFbmFub3MYAiABKAVSBW5hbm9zQoUBChNjb20uZ29vZ2xlLnByb3RvYnVmQg5UaW1lc3RhbXBQcm90b1ABWjJnb29nbGUuZ29sYW5nLm9yZy9wcm90b2J1Zi90eXBlcy9rbm93bi90aW1lc3RhbXBwYvgBAaICA0dQQqoCHkdvb2dsZS5Qcm90b2J1Zi5XZWxsS25vd25UeXBlc2IGcHJvdG8zCsYCChlmb3hnbG92ZS9Qb2ludENsb3VkLnByb3RvEghmb3hnbG92ZRohZm94Z2xvdmUvUGFja2VkRWxlbWVudEZpZWxkLnByb3RvGhNmb3hnbG92ZS9Qb3NlLnByb3RvGh9nb29nbGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvIr0BCgpQb2ludENsb3VkEi0KCXRpbWVzdGFtcBgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASEAoIZnJhbWVfaWQYAiABKAkSHAoEcG9zZRgDIAEoCzIOLmZveGdsb3ZlLlBvc2USFAoMcG9pbnRfc3RyaWRlGAQgASgHEiwKBmZpZWxkcxgFIAMoCzIcLmZveGdsb3ZlLlBhY2tlZEVsZW1lbnRGaWVsZBIMCgRkYXRhGAYgASgMYgZwcm90bzM=",
  ),
});

function bytes(base64: string): Uint8Array {
  return Uint8Array.from(atob(base64), (char) => char.charCodeAt(0));
}
