"""
Generates the Voodo design system's color palette for the Python package and
the App's utilities package.

The App renders palette colors from CSS variables generated by
``@voxel51/voodo``, but the default color pool was hardcoded in two more
places -- ``fiftyone/constants.py`` and ``app/packages/utilities/src/color.ts``
-- which drift silently whenever the design system changes. This script makes
the design system the source of truth for all three.

Each output is a wholly generated module that its consumer imports, rather
than a block edited into an existing file. Nothing here parses the files it
writes, and the generated modules are type-checked and imported like any
other, so a rename or a shape change fails at build time instead of silently
producing a wrong palette. ``--check`` covers the one thing types cannot:
whether the committed values are stale with respect to the tokens.

Usage::

    # regenerate both modules
    python tools/sync_voodoo_palette.py

    # exit 1 if either is out of date (CI)
    python tools/sync_voodoo_palette.py --check

    # print the modules instead of writing them
    python tools/sync_voodoo_palette.py --print

The palette is theme-aware in the App but not on the server, so the dark-mode
values are used -- dark is the App's default theme. Light and dark palettes are
identical today; if they ever diverge, this choice needs revisiting alongside
whatever makes the server theme-aware.

| Copyright 2017-2025, Voxel51, Inc.
| `voxel51.com <https://voxel51.com/>`_
|
"""

import argparse
import json
import os
import sys


# The ordered palette slots handed out by the App, mirroring PALETTE_POOL_KEYS
# in @voxel51/voodo (src/theme/useColorPalette.ts)
POOL_SLOTS = [str(i) for i in range(1, 13)]

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PYTHON_TARGET = os.path.join(REPO_ROOT, "fiftyone", "_voodoo_palette.py")

TYPESCRIPT_TARGET = os.path.join(
    REPO_ROOT, "app", "packages", "utilities", "src", "voodooPalette.ts"
)

# Where the tokens land depends on how the App's node_modules were hoisted, so
# check the workspace root first and then the package that declares the
# dependency
TOKENS_CANDIDATES = [
    os.path.join(
        REPO_ROOT, "app", "node_modules", "@voxel51", "voodo", "tokens.json"
    ),
    os.path.join(
        REPO_ROOT,
        "app",
        "node_modules",
        "@voxel51",
        "voodo",
        "dist",
        "tokens.json",
    ),
    os.path.join(
        REPO_ROOT,
        "app",
        "packages",
        "components",
        "node_modules",
        "@voxel51",
        "voodo",
        "dist",
        "tokens.json",
    ),
]

_PYTHON_TEMPLATE = '''"""
Voodo design system color palette.

AUTO-GENERATED by ``tools/sync_voodoo_palette.py`` -- do not edit by hand.
Run that script to pick up design system changes.

| Copyright 2017-2025, Voxel51, Inc.
| `voxel51.com <https://voxel51.com/>`_
|
"""

# The App's default color pool, in the order colors are handed out
COLOR_POOL = [
{entries}
]
'''

_TYPESCRIPT_TEMPLATE = """/**
 * Voodo design system color palette.
 *
 * AUTO-GENERATED by `tools/sync_voodoo_palette.py` -- do not edit by hand.
 * Run that script to pick up design system changes.
 *
 * Copyright 2017-2026, Voxel51, Inc.
 */

/** The App's default color pool, in the order colors are handed out. */
export const VOODOO_COLOR_POOL: readonly string[] = [
{entries}
];
"""


def _find_tokens(explicit=None, skip_if_missing=False):
    """Locates the Voodo ``tokens.json``.

    Args:
        explicit (None): an explicit path, e.g. a local design-system checkout
        skip_if_missing (False): return ``None`` instead of raising when the
            tokens cannot be found

    Returns:
        the path to ``tokens.json``, or ``None``
    """
    if explicit is not None:
        if not os.path.isfile(explicit):
            raise SystemExit("No tokens.json at '%s'" % explicit)

        return explicit

    env = os.environ.get("VOODO_TOKENS")
    if env:
        return _find_tokens(env)

    for path in TOKENS_CANDIDATES:
        if os.path.isfile(path):
            return path

    if skip_if_missing:
        return None

    raise SystemExit(
        "Could not find @voxel51/voodo tokens.json. Install the App's "
        "dependencies (`yarn install` in app/), or pass --tokens with the "
        "path to a design-system checkout's src/theme/tokens.json."
    )


def _load_palette(tokens_path):
    """Extracts the ordered dark-mode palette from the Voodo tokens.

    Args:
        tokens_path: the path to ``tokens.json``

    Returns:
        a list of ``(hex, label)`` tuples in pool order
    """
    with open(tokens_path, "rt") as f:
        tokens = json.load(f)

    try:
        palette = tokens["colors"]["dark"]["content"]["palette"]
    except KeyError:
        raise SystemExit(
            "Unexpected token shape in '%s': no colors.dark.content.palette. "
            "The design system's token tree may have been restructured."
            % tokens_path
        )

    # Reverse the primitive scales so each slot can be labeled with the scale
    # step it came from ("purple 600"), which is how the design system talks
    # about these colors
    labels = {}
    for scale, steps in tokens.get("primitives", {}).items():
        for step, value in steps.items():
            labels.setdefault(value, "%s %s" % (scale, step))

    pool = []
    for slot in POOL_SLOTS:
        if slot not in palette:
            raise SystemExit(
                "Palette slot %s missing from '%s'" % (slot, tokens_path)
            )

        color = palette[slot]
        pool.append((color, labels.get(color, "unmapped")))

    return pool


def _render_python(pool):
    """Renders the generated Python module.

    Args:
        pool: a list of ``(hex, label)`` tuples

    Returns:
        the module source, black-formatted at 79 columns
    """
    entries = [
        '    "%s",  # %d: %s' % (color, i, label)
        for i, (color, label) in enumerate(pool, 1)
    ]

    return _PYTHON_TEMPLATE.format(entries="\n".join(entries))


def _render_typescript(pool):
    """Renders the generated TypeScript module.

    Args:
        pool: a list of ``(hex, label)`` tuples

    Returns:
        the module source, prettier-formatted
    """
    entries = [
        '  "%s", // %d: %s' % (color, i, label)
        for i, (color, label) in enumerate(pool, 1)
    ]

    return _TYPESCRIPT_TEMPLATE.format(entries="\n".join(entries))


def _targets(pool):
    """Pairs each output path with its rendered contents.

    Args:
        pool: a list of ``(hex, label)`` tuples

    Returns:
        a list of ``(path, contents)`` tuples
    """
    return [
        (PYTHON_TARGET, _render_python(pool)),
        (TYPESCRIPT_TARGET, _render_typescript(pool)),
    ]


def _read(path):
    """Reads ``path``, or returns ``None`` if it does not exist."""
    if not os.path.isfile(path):
        return None

    with open(path, "rt") as f:
        return f.read()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if a generated module is out of date",
    )
    parser.add_argument(
        "--print",
        action="store_true",
        dest="print_only",
        help="print the generated modules instead of writing them",
    )
    parser.add_argument(
        "--tokens",
        default=None,
        help="path to a Voodo tokens.json, e.g. from a local checkout",
    )
    parser.add_argument(
        "--skip-if-missing",
        action="store_true",
        help=(
            "succeed quietly when the installed @voxel51/voodo predates the "
            "tokens.json export, rather than failing (for CI)"
        ),
    )
    args = parser.parse_args()

    tokens_path = _find_tokens(args.tokens, args.skip_if_missing)
    if tokens_path is None:
        print(
            "No @voxel51/voodo tokens.json found; skipping palette sync. "
            "Upgrade @voxel51/voodo to a version that exports tokens.json."
        )
        return 0

    targets = _targets(_load_palette(tokens_path))

    if args.print_only:
        for path, contents in targets:
            print("# %s\n" % os.path.relpath(path, REPO_ROOT))
            print(contents)

        return 0

    stale = [
        (path, contents)
        for path, contents in targets
        if _read(path) != contents
    ]

    if not stale:
        print("Palette modules are up to date with %s" % tokens_path)
        return 0

    if args.check:
        print(
            "Palette modules are out of date with %s:\n%s\n"
            "Run `python tools/sync_voodoo_palette.py` and commit the result."
            % (
                tokens_path,
                "\n".join(
                    "  %s" % os.path.relpath(path, REPO_ROOT)
                    for path, _ in stale
                ),
            ),
            file=sys.stderr,
        )
        return 1

    for path, contents in stale:
        with open(path, "wt") as f:
            f.write(contents)

        print("Wrote %s" % os.path.relpath(path, REPO_ROOT))

    return 0


if __name__ == "__main__":
    sys.exit(main())
