version: "3.2"
services:
  pypi-server:
    command: ["-P", "/data/htpasswd.txt", "-a", "update", "/data/packages"]
    image: pypiserver/pypiserver:latest
    ports:
      - "127.0.0.1:5159:8080"
    restart: always
    volumes:
      - type: volume
        source: packages
        target: /data/packages
      - type: bind
        source: ./htpasswd.txt
        target: /data/htpasswd.txt
volumes:
  packages:
