name: Build GUI

on:
  push:
    branches:
      # - develop
      - rel-*
      - release-*
      - gui-*
      - github-actions-*
    tags:
      - gui-v*
    paths:
      - electron/**
      - package/gui/**
      - .github/workflows/build-gui.yml
  pull_request:
    branches:
      # - develop
      - rel-*
      - release-*
    paths:
      - electron/**
      - package/gui/**
      - .github/workflows/build-gui.yml

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone fiftyone
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip setuptools wheel
      - name: Fetch dependency cache
        uses: actions/cache@v2
        with:
          path: electron/node_modules
          key: npm-${{ hashFiles('electron/package.json') }}
          restore-keys: |
            npm-${{ hashFiles('electron/package.json') }}
            npm-
      - name: Install dependencies
        working-directory: electron
        run: yarn
      - name: Package GUI (Linux)
        working-directory: electron
        run: yarn package-linux --publish never
      - name: Package GUI (macOS)
        working-directory: electron
        run: yarn package-mac --publish never
      - name: Package GUI (Windows)
        working-directory: electron
        # from https://www.electron.build/multi-platform-build#docker
        # removed node_modules mount to use existing packages
        run: |
          docker run --rm \
           --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_') \
           --env ELECTRON_CACHE="/root/.cache/electron" \
           --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" \
           -v ${PWD}:/project \
           -v ~/.cache/electron:/root/.cache/electron \
           -v ~/.cache/electron-builder:/root/.cache/electron-builder \
           electronuserland/builder:wine \
           yarn package-win --publish never
      - name: Build wheel (Linux)
        working-directory: package/gui
        run: python setup.py bdist_wheel --plat-name linux
      - name: Build wheel (macOS)
        working-directory: package/gui
        run: python setup.py bdist_wheel --plat-name mac
      - name: Build wheel (Windows)
        working-directory: package/gui
        run: python setup.py bdist_wheel --plat-name win
      - name: Upload wheel (Linux)
        uses: actions/upload-artifact@v2
        with:
          name: wheel-linux
          path: package/gui/dist/*linux*.whl
      - name: Upload wheel (macOS)
        uses: actions/upload-artifact@v2
        with:
          name: wheel-macos
          path: package/gui/dist/*macos*.whl
      - name: Upload wheel (Windows)
        uses: actions/upload-artifact@v2
        with:
          name: wheel-windows
          path: package/gui/dist/*win*.whl
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Clone fiftyone
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Check tag
        if: startsWith(github.ref, 'refs/tags/gui-v')
        run: |
          python .github/tools/check-setup-version.py package/gui/setup.py $(echo ${{ github.ref }} | sed 's/refs\/tags\/gui-v//')

  publish:
    runs-on: ubuntu-18.04
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/gui-v')
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v2
        with:
          path: downloads
      - name: Install dependencies
        run: |
          pip3 install twine
      - name: Upload to pypi.voxel51.com
        env:
          TWINE_USERNAME: voxel51-ci
          TWINE_PASSWORD: ${{ secrets.FIFTYONE_GITHUB_TOKEN }}
          TWINE_NON_INTERACTIVE: 1
        run: |
          python3 -m twine upload --repository-url https://pypi.voxel51.com downloads/wheel-*/*.whl
