name: Build GUI

on:
  push:
    paths:
      - electron/
      - package/gui/
      - .github/workflows/build-gui.yml

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone fiftyone
        uses: actions/checkout@v1
      - name: Fetch dependency cache
        uses: actions/cache@v2
        with:
          key: electron-cache
          path: electron/node_modules
      - name: Clone submodules
        run: |
          git submodule set-url electron/app/player51 https://${{ secrets.FIFTYONE_GITHUB_TOKEN }}@github.com/voxel51/player51
          git submodule update --init
      - name: Install dependencies
        working-directory: electron
        run: yarn
      - name: Build GUI
        working-directory: electron
        run: yarn build
      - name: Package GUI (Linux)
        working-directory: electron
        run: yarn package-linux --publish never
      - name: Package GUI (macOS)
        working-directory: electron
        run: yarn package-mac --publish never
      - name: Build wheel (Linux)
        working-directory: package/gui
        run: python3 setup.py bdist_wheel --plat-name linux
      - name: Build wheel (macOS)
        working-directory: package/gui
        run: python3 setup.py bdist_wheel --plat-name macOS
      - name: Upload wheel (Linux)
        uses: actions/upload-artifact@v2
        with:
          name: wheel-linux
          path: package/gui/dist/*linux*.whl
      - name: Upload wheel (macOS)
        uses: actions/upload-artifact@v2
        with:
          name: wheel-macos
          path: package/gui/dist/*macos*.whl

  publish:
    runs-on: ubuntu-20.04
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/gui-v')
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v2
        with:
          path: downloads
      - name: Install dependencies
        run: |
          pip3 install twine
      - name: Upload to pypi.voxel51.com
        env:
          TWINE_USERNAME: voxel51-ci
          TWINE_PASSWORD: ${{ secrets.FIFTYONE_GITHUB_TOKEN }}
          TWINE_NON_INTERACTIVE: 1
        run: |
          python3 -m twine upload --repository-url https://pypi.voxel51.com downloads/wheel-*/*.whl
