name: Chromatic
on:
  push:
    branches:
      - develop
      - rel-*
      - release-*
      - github-actions-*
    tags:
      - v*
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches:
      - develop
      - rel-*
      - release-*
    paths:
      - electron/**
      - .github/workflows/chromatic.yml

jobs:
  chromatic:
    runs-on: ubuntu-18.04
    if: github.event.pull_request.draft == false
    steps:
      - name: Clone fiftyone
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Fetch dependency cache
        uses: actions/cache@v2
        with:
          key: electron-cache
          path: electron/node_modules
      - name: Install dependencies
        working-directory: electron
        run: yarn
      - name: Publish storybook
        working-directory: electron
        run: yarn chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}
