name: Test App

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop
  push:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone fiftyone
        uses: actions/checkout@v2
      - name: Fetch app dependency cache
        uses: actions/cache@v2
        with:
          path: app/node_modules
          key: npm-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            npm-${{ hashFiles('yarn.lock') }}
            npm-
      - name: Install app
        run: cd app && yarn install
      - name: Run tests
        run: cd app && yarn test --coverage
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
          flags: state-unit-tests
          fail_ci_if_error: true
